server:
  port: 7002


spring:
  application:
    name: eureka7002.com

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责即使维护服务实例，并不需要去检索服务
    fetch-registry: false
    #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/