server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #路由配置
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名 进行注册路由
          enabled: true
      routes:
          #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          #断言。路由相匹配的进行路径
          predicates:
            - Path=/payment/get/**

        #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh2
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          #断言。路由相匹配的进行路径
          predicates:
            #断言，路径相匹配的进行路由
            - Path=/payment/lb/**
            #断言，时间之后才能请求到，否则404
            - After=2020-04-06T23:06:18.071+08:00[Asia/Shanghai]
            #断言，Cookie必须有key:value才执行，否则404
            #- Cookie=username,zzyy
            #断言，请求头要有X-Request-Id属性，并且值为整数的正则表达式
            #- Header=X-Request-Id,\d+
            #断言，请求的类型要求，必须是get请求
            #- Method=GET
            #断言，要有参数名username并且值是整数
            #- Query=username,\d+


eureka:
  client:
    #表示是否将自己注册进服务端EurekaService，默认true，因为自身为eureka客户端
    register-with-eureka: true

    #是否从EurekaService抓取已有的注册信息，默认true, 单节点无所谓，
    #集群必须设置为true,才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #指定要注册进入 的EurekaService地址
      #单机版
      #      defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
