server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  #把本服务注册进下面的nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
