server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    #表示是否将自己注册进服务端EurekaService，默认true，因为自身为eureka客户端
    register-with-eureka: true

    #是否从EurekaService抓取已有的注册信息，默认true, 单节点无所谓，
    #集群必须设置为true,才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #指定要注册进入 的EurekaService地址
      #单机版
      #      defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

